/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

/**
 *
 * @author Admin
 */
public class LapTheDocGia extends javax.swing.JFrame {

    /**
     * Creates new form LapTheDocGia
     */
    public LapTheDocGia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PN_lapthedocgia_mainmenu = new javax.swing.JPanel();
        BT_trangchu = new javax.swing.JButton();
        BT_sach = new javax.swing.JButton();
        BT_docgia = new javax.swing.JButton();
        BT_muontrasach = new javax.swing.JButton();
        BT_thongke = new javax.swing.JButton();
        BT_hethong = new javax.swing.JButton();
        BT_taikhoan = new javax.swing.JButton();
        BT_dangxuat = new javax.swing.JButton();
        PN_lapthedocgia_menu = new javax.swing.JPanel();
        LB_docgiamenu = new javax.swing.JLabel();
        BT_lapthedocgia = new javax.swing.JButton();
        BT_thongtindocgia = new javax.swing.JButton();
        PN_lapthedocgia_info = new javax.swing.JPanel();
        PN_lapthedocgia_info_chitiet = new javax.swing.JPanel();
        LB_madocgia = new javax.swing.JLabel();
        LB_hovaten = new javax.swing.JLabel();
        TF_hovaten = new javax.swing.JTextField();
        TF_madocgia = new javax.swing.JTextField();
        LB_cmnd = new javax.swing.JLabel();
        LB_mail = new javax.swing.JLabel();
        TF_mail = new javax.swing.JTextField();
        LB_diachi = new javax.swing.JLabel();
        TF_diachi = new javax.swing.JTextField();
        LB_ngaylapthe = new javax.swing.JLabel();
        LB_ngaysinh = new javax.swing.JLabel();
        LB_gioitinh = new javax.swing.JLabel();
        LB_loaidocgia = new javax.swing.JLabel();
        TF_cmnd = new javax.swing.JTextField();
        FF_ngaylapthe = new javax.swing.JFormattedTextField();
        FF_ngaysinh = new javax.swing.JFormattedTextField();
        CB_gioitinh = new javax.swing.JComboBox<>();
        CB_loaidocgia = new javax.swing.JComboBox<>();
        BT_save = new javax.swing.JButton();
        BT_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PN_lapthedocgia_mainmenu.setBackground(new java.awt.Color(51, 51, 255));
        PN_lapthedocgia_mainmenu.setAlignmentX(0.0F);
        PN_lapthedocgia_mainmenu.setAlignmentY(0.0F);

        BT_trangchu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_trangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trangchu.png"))); // NOI18N
        BT_trangchu.setText("Trang Chủ");
        BT_trangchu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BT_trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_trangchuActionPerformed(evt);
            }
        });

        BT_sach.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_sach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sach.png"))); // NOI18N
        BT_sach.setText("Sách");
        BT_sach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BT_docgia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_docgia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/docgia.png"))); // NOI18N
        BT_docgia.setText("Độc Giả");
        BT_docgia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BT_muontrasach.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_muontrasach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/muonsach.png"))); // NOI18N
        BT_muontrasach.setText("Mượn Trả Sách");
        BT_muontrasach.setAlignmentY(0.0F);
        BT_muontrasach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BT_thongke.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thongke.png"))); // NOI18N
        BT_thongke.setText("Thống Kê");
        BT_thongke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BT_hethong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_hethong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hethong.png"))); // NOI18N
        BT_hethong.setText("Hệ Thống");
        BT_hethong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BT_hethong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_hethongActionPerformed(evt);
            }
        });

        BT_taikhoan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_taikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/taikhoan.png"))); // NOI18N
        BT_taikhoan.setText("Tài Khoản");
        BT_taikhoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BT_dangxuat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dangxuat.png"))); // NOI18N
        BT_dangxuat.setText("Đăng Xuất");
        BT_dangxuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout PN_lapthedocgia_mainmenuLayout = new javax.swing.GroupLayout(PN_lapthedocgia_mainmenu);
        PN_lapthedocgia_mainmenu.setLayout(PN_lapthedocgia_mainmenuLayout);
        PN_lapthedocgia_mainmenuLayout.setHorizontalGroup(
            PN_lapthedocgia_mainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BT_sach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BT_docgia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BT_muontrasach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BT_thongke, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BT_hethong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BT_taikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BT_dangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BT_trangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PN_lapthedocgia_mainmenuLayout.setVerticalGroup(
            PN_lapthedocgia_mainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_lapthedocgia_mainmenuLayout.createSequentialGroup()
                .addComponent(BT_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BT_sach, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BT_docgia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BT_muontrasach, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BT_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BT_hethong, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BT_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BT_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PN_lapthedocgia_menu.setBackground(new java.awt.Color(102, 153, 255));

        LB_docgiamenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/docgiamain.png"))); // NOI18N

        BT_lapthedocgia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_lapthedocgia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lapthedocgia.png"))); // NOI18N
        BT_lapthedocgia.setText("Lập Thẻ Độc Giả");

        BT_thongtindocgia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_thongtindocgia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thongtindocgia.png"))); // NOI18N
        BT_thongtindocgia.setText("Thông Tin Độc Giả");

        javax.swing.GroupLayout PN_lapthedocgia_menuLayout = new javax.swing.GroupLayout(PN_lapthedocgia_menu);
        PN_lapthedocgia_menu.setLayout(PN_lapthedocgia_menuLayout);
        PN_lapthedocgia_menuLayout.setHorizontalGroup(
            PN_lapthedocgia_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_lapthedocgia_menuLayout.createSequentialGroup()
                .addComponent(LB_docgiamenu)
                .addGap(128, 128, 128)
                .addComponent(BT_lapthedocgia)
                .addGap(197, 197, 197)
                .addComponent(BT_thongtindocgia)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PN_lapthedocgia_menuLayout.setVerticalGroup(
            PN_lapthedocgia_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_lapthedocgia_menuLayout.createSequentialGroup()
                .addComponent(LB_docgiamenu)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN_lapthedocgia_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PN_lapthedocgia_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BT_thongtindocgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_lapthedocgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        LB_madocgia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_madocgia.setText("Mã độc giả");

        LB_hovaten.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_hovaten.setText("Họ và tên");

        TF_hovaten.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        TF_madocgia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        LB_cmnd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_cmnd.setText("CMND");

        LB_mail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_mail.setText("Mail");

        TF_mail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        TF_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_mailActionPerformed(evt);
            }
        });

        LB_diachi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_diachi.setText("Địa chỉ");

        TF_diachi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        LB_ngaylapthe.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_ngaylapthe.setText("Ngày lập thẻ");

        LB_ngaysinh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_ngaysinh.setText("Ngày sinh");

        LB_gioitinh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_gioitinh.setText("Giới tính");

        LB_loaidocgia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_loaidocgia.setText("Loại độc giả");

        TF_cmnd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        FF_ngaylapthe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        FF_ngaylapthe.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        FF_ngaysinh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        FF_ngaysinh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        CB_gioitinh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CB_gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Không xác định", " " }));

        CB_loaidocgia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CB_loaidocgia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout PN_lapthedocgia_info_chitietLayout = new javax.swing.GroupLayout(PN_lapthedocgia_info_chitiet);
        PN_lapthedocgia_info_chitiet.setLayout(PN_lapthedocgia_info_chitietLayout);
        PN_lapthedocgia_info_chitietLayout.setHorizontalGroup(
            PN_lapthedocgia_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_lapthedocgia_info_chitietLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(PN_lapthedocgia_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LB_diachi)
                    .addComponent(LB_mail)
                    .addComponent(LB_cmnd)
                    .addComponent(LB_hovaten)
                    .addComponent(LB_madocgia))
                .addGap(40, 40, 40)
                .addGroup(PN_lapthedocgia_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PN_lapthedocgia_info_chitietLayout.createSequentialGroup()
                        .addGroup(PN_lapthedocgia_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TF_hovaten)
                            .addComponent(TF_mail)
                            .addComponent(TF_cmnd)
                            .addComponent(TF_madocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PN_lapthedocgia_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PN_lapthedocgia_info_chitietLayout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addGroup(PN_lapthedocgia_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LB_ngaysinh)
                                    .addComponent(LB_ngaylapthe)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN_lapthedocgia_info_chitietLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PN_lapthedocgia_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB_gioitinh, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LB_loaidocgia, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PN_lapthedocgia_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CB_gioitinh, 0, 237, Short.MAX_VALUE)
                            .addComponent(FF_ngaysinh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FF_ngaylapthe, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CB_loaidocgia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(TF_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        PN_lapthedocgia_info_chitietLayout.setVerticalGroup(
            PN_lapthedocgia_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_lapthedocgia_info_chitietLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(PN_lapthedocgia_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_madocgia)
                    .addComponent(TF_madocgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_ngaylapthe)
                    .addComponent(FF_ngaylapthe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PN_lapthedocgia_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_hovaten)
                    .addComponent(TF_hovaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_ngaysinh)
                    .addComponent(FF_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PN_lapthedocgia_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_cmnd)
                    .addComponent(LB_gioitinh)
                    .addComponent(TF_cmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PN_lapthedocgia_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_mail)
                    .addComponent(TF_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_loaidocgia)
                    .addComponent(CB_loaidocgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PN_lapthedocgia_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_diachi)
                    .addComponent(TF_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        BT_save.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BT_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/savebt1.png"))); // NOI18N
        BT_save.setText("Lưu Lại");

        BT_reset.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BT_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/savebt.png"))); // NOI18N
        BT_reset.setText("Làm Mới");

        javax.swing.GroupLayout PN_lapthedocgia_infoLayout = new javax.swing.GroupLayout(PN_lapthedocgia_info);
        PN_lapthedocgia_info.setLayout(PN_lapthedocgia_infoLayout);
        PN_lapthedocgia_infoLayout.setHorizontalGroup(
            PN_lapthedocgia_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_lapthedocgia_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PN_lapthedocgia_info_chitiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN_lapthedocgia_infoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BT_save)
                .addGap(97, 97, 97)
                .addComponent(BT_reset)
                .addGap(185, 185, 185))
        );
        PN_lapthedocgia_infoLayout.setVerticalGroup(
            PN_lapthedocgia_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_lapthedocgia_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PN_lapthedocgia_info_chitiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PN_lapthedocgia_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_save)
                    .addComponent(BT_reset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PN_lapthedocgia_mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PN_lapthedocgia_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PN_lapthedocgia_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN_lapthedocgia_mainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PN_lapthedocgia_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PN_lapthedocgia_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_trangchuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_trangchuActionPerformed

    private void BT_hethongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_hethongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_hethongActionPerformed

    private void TF_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_mailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LapTheDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LapTheDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LapTheDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LapTheDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                new Runnable() 
                {
            public void runLB_docgiamenu{
                    new LapTheDocGia().setVisible(true);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_dangxuat;
    private javax.swing.JButton BT_docgia;
    private javax.swing.JButton BT_hethong;
    private javax.swing.JButton BT_lapthedocgia;
    private javax.swing.JButton BT_muontrasach;
    private javax.swing.JButton BT_reset;
    private javax.swing.JButton BT_sach;
    private javax.swing.JButton BT_save;
    private javax.swing.JButton BT_taikhoan;
    private javax.swing.JButton BT_thongke;
    private javax.swing.JButton BT_thongtindocgia;
    private javax.swing.JButton BT_trangchu;
    private javax.swing.JComboBox<String> CB_gioitinh;
    private javax.swing.JComboBox<String> CB_loaidocgia;
    private javax.swing.JFormattedTextField FF_ngaylapthe;
    private javax.swing.JFormattedTextField FF_ngaysinh;
    private javax.swing.JLabel LB_cmnd;
    private javax.swing.JLabel LB_diachi;
    private javax.swing.JLabel LB_docgiamenu;
    private javax.swing.JLabel LB_gioitinh;
    private javax.swing.JLabel LB_hovaten;
    private javax.swing.JLabel LB_loaidocgia;
    private javax.swing.JLabel LB_madocgia;
    private javax.swing.JLabel LB_mail;
    private javax.swing.JLabel LB_ngaylapthe;
    private javax.swing.JLabel LB_ngaysinh;
    private javax.swing.JPanel PN_lapthedocgia_info;
    private javax.swing.JPanel PN_lapthedocgia_info_chitiet;
    private javax.swing.JPanel PN_lapthedocgia_mainmenu;
    private javax.swing.JPanel PN_lapthedocgia_menu;
    private javax.swing.JTextField TF_cmnd;
    private javax.swing.JTextField TF_diachi;
    private javax.swing.JTextField TF_hovaten;
    private javax.swing.JTextField TF_madocgia;
    private javax.swing.JTextField TF_mail;
    // End of variables declaration//GEN-END:variables
}
