/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

/**
 *
 * @author Admin
 */
public class ThemSach extends javax.swing.JFrame {

    /**
     * Creates new form ThemSach
     */
    public ThemSach() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PN_themsach_mainmenu = new javax.swing.JPanel();
        BT_trangchu = new javax.swing.JButton();
        BT_sach = new javax.swing.JButton();
        BT_docgia = new javax.swing.JButton();
        BT_muontrasach = new javax.swing.JButton();
        BT_thongke = new javax.swing.JButton();
        BT_hethong = new javax.swing.JButton();
        BT_taikhoan = new javax.swing.JButton();
        BT_dangxuat = new javax.swing.JButton();
        PN_themsach_menu = new javax.swing.JPanel();
        LB_Sach_menu = new javax.swing.JLabel();
        BT_themsach = new javax.swing.JButton();
        BT_thongtinsach = new javax.swing.JButton();
        PN_themsach_info = new javax.swing.JPanel();
        PN_themsach_info_chitiet = new javax.swing.JPanel();
        LB_masach = new javax.swing.JLabel();
        LB_tensach = new javax.swing.JLabel();
        TF_tensach = new javax.swing.JTextField();
        TF_masach = new javax.swing.JTextField();
        LB_tacgia = new javax.swing.JLabel();
        LB_nxb = new javax.swing.JLabel();
        TF_nxb = new javax.swing.JTextField();
        LB_namxuatban = new javax.swing.JLabel();
        TF_namxuatban = new javax.swing.JTextField();
        LB_ngaynhap = new javax.swing.JLabel();
        FF_ngaynhap = new javax.swing.JFormattedTextField();
        LB_theloai = new javax.swing.JLabel();
        CB_theloai = new javax.swing.JComboBox<>();
        LB_trigia = new javax.swing.JLabel();
        LB_soluong = new javax.swing.JLabel();
        SN_soluong = new javax.swing.JSpinner();
        TF_tacgia = new javax.swing.JTextField();
        FF_trigia = new javax.swing.JFormattedTextField();
        BT_save = new javax.swing.JButton();
        BT_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PN_themsach_mainmenu.setBackground(new java.awt.Color(51, 51, 255));
        PN_themsach_mainmenu.setAlignmentX(0.0F);
        PN_themsach_mainmenu.setAlignmentY(0.0F);

        BT_trangchu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_trangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trangchu.png"))); // NOI18N
        BT_trangchu.setText("Trang Chủ");
        BT_trangchu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BT_trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_trangchuActionPerformed(evt);
            }
        });

        BT_sach.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_sach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sach.png"))); // NOI18N
        BT_sach.setText("Sách");
        BT_sach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BT_docgia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_docgia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/docgia.png"))); // NOI18N
        BT_docgia.setText("Độc Giả");
        BT_docgia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BT_muontrasach.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_muontrasach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/muonsach.png"))); // NOI18N
        BT_muontrasach.setText("Mượn Trả Sách");
        BT_muontrasach.setAlignmentY(0.0F);
        BT_muontrasach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BT_thongke.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thongke.png"))); // NOI18N
        BT_thongke.setText("Thống Kê");
        BT_thongke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BT_hethong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_hethong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hethong.png"))); // NOI18N
        BT_hethong.setText("Hệ Thống");
        BT_hethong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BT_hethong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_hethongActionPerformed(evt);
            }
        });

        BT_taikhoan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_taikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/taikhoan.png"))); // NOI18N
        BT_taikhoan.setText("Tài Khoản");
        BT_taikhoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BT_dangxuat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dangxuat.png"))); // NOI18N
        BT_dangxuat.setText("Đăng Xuất");
        BT_dangxuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout PN_themsach_mainmenuLayout = new javax.swing.GroupLayout(PN_themsach_mainmenu);
        PN_themsach_mainmenu.setLayout(PN_themsach_mainmenuLayout);
        PN_themsach_mainmenuLayout.setHorizontalGroup(
            PN_themsach_mainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BT_sach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BT_docgia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BT_muontrasach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BT_thongke, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BT_hethong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BT_taikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BT_dangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BT_trangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PN_themsach_mainmenuLayout.setVerticalGroup(
            PN_themsach_mainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_themsach_mainmenuLayout.createSequentialGroup()
                .addComponent(BT_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BT_sach, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BT_docgia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BT_muontrasach, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BT_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BT_hethong, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BT_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BT_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PN_themsach_menu.setBackground(new java.awt.Color(51, 102, 255));

        LB_Sach_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/themsachmain.png"))); // NOI18N

        BT_themsach.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_themsach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/themsach.png"))); // NOI18N
        BT_themsach.setText("Thêm Sách");

        BT_thongtinsach.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BT_thongtinsach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thongtinsach.png"))); // NOI18N
        BT_thongtinsach.setText("Thông Tin Sách");

        javax.swing.GroupLayout PN_themsach_menuLayout = new javax.swing.GroupLayout(PN_themsach_menu);
        PN_themsach_menu.setLayout(PN_themsach_menuLayout);
        PN_themsach_menuLayout.setHorizontalGroup(
            PN_themsach_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_themsach_menuLayout.createSequentialGroup()
                .addComponent(LB_Sach_menu)
                .addGap(130, 130, 130)
                .addComponent(BT_themsach, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199)
                .addComponent(BT_thongtinsach)
                .addGap(0, 204, Short.MAX_VALUE))
        );
        PN_themsach_menuLayout.setVerticalGroup(
            PN_themsach_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_themsach_menuLayout.createSequentialGroup()
                .addComponent(LB_Sach_menu)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN_themsach_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PN_themsach_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BT_thongtinsach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_themsach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        LB_masach.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_masach.setText("Mã sách");

        LB_tensach.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_tensach.setText("Tên sách");

        TF_tensach.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        TF_masach.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        LB_tacgia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_tacgia.setText("Tác giả");

        LB_nxb.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_nxb.setText("Nhà xuất bản");

        TF_nxb.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        TF_nxb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_nxbActionPerformed(evt);
            }
        });

        LB_namxuatban.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_namxuatban.setText("Năm xuất bản");

        TF_namxuatban.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        LB_ngaynhap.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_ngaynhap.setText("Ngày nhập");

        FF_ngaynhap.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyy"))));
        FF_ngaynhap.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        LB_theloai.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_theloai.setText("Thể loại");

        CB_theloai.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CB_theloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LB_trigia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_trigia.setText("Trị giá");

        LB_soluong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LB_soluong.setText("Số lượng");

        SN_soluong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        TF_tacgia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        FF_trigia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        FF_trigia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        javax.swing.GroupLayout PN_themsach_info_chitietLayout = new javax.swing.GroupLayout(PN_themsach_info_chitiet);
        PN_themsach_info_chitiet.setLayout(PN_themsach_info_chitietLayout);
        PN_themsach_info_chitietLayout.setHorizontalGroup(
            PN_themsach_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_themsach_info_chitietLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(PN_themsach_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LB_namxuatban)
                    .addComponent(LB_nxb)
                    .addComponent(LB_tacgia)
                    .addComponent(LB_tensach)
                    .addComponent(LB_masach))
                .addGap(40, 40, 40)
                .addGroup(PN_themsach_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF_masach)
                    .addComponent(TF_tensach)
                    .addComponent(TF_nxb, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(TF_namxuatban)
                    .addComponent(TF_tacgia))
                .addGap(209, 209, 209)
                .addGroup(PN_themsach_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_ngaynhap)
                    .addComponent(LB_theloai)
                    .addComponent(LB_trigia)
                    .addComponent(LB_soluong))
                .addGap(47, 47, 47)
                .addGroup(PN_themsach_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FF_ngaynhap)
                    .addComponent(CB_theloai, 0, 259, Short.MAX_VALUE)
                    .addComponent(SN_soluong)
                    .addComponent(FF_trigia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PN_themsach_info_chitietLayout.setVerticalGroup(
            PN_themsach_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_themsach_info_chitietLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(PN_themsach_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_masach)
                    .addComponent(TF_masach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_ngaynhap)
                    .addComponent(FF_ngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PN_themsach_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_tensach)
                    .addComponent(TF_tensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_theloai)
                    .addComponent(CB_theloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PN_themsach_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_tacgia)
                    .addComponent(LB_trigia)
                    .addComponent(TF_tacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FF_trigia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PN_themsach_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_nxb)
                    .addComponent(TF_nxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_soluong)
                    .addComponent(SN_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PN_themsach_info_chitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_namxuatban)
                    .addComponent(TF_namxuatban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        BT_save.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BT_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/savebt1.png"))); // NOI18N
        BT_save.setText("Lưu Lại");

        BT_reset.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BT_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/savebt.png"))); // NOI18N
        BT_reset.setText("Làm Mới");

        javax.swing.GroupLayout PN_themsach_infoLayout = new javax.swing.GroupLayout(PN_themsach_info);
        PN_themsach_info.setLayout(PN_themsach_infoLayout);
        PN_themsach_infoLayout.setHorizontalGroup(
            PN_themsach_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_themsach_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PN_themsach_info_chitiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN_themsach_infoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BT_save)
                .addGap(97, 97, 97)
                .addComponent(BT_reset)
                .addGap(185, 185, 185))
        );
        PN_themsach_infoLayout.setVerticalGroup(
            PN_themsach_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN_themsach_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PN_themsach_info_chitiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PN_themsach_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_save)
                    .addComponent(BT_reset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PN_themsach_mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PN_themsach_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(PN_themsach_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN_themsach_mainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PN_themsach_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PN_themsach_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_trangchuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_trangchuActionPerformed

    private void BT_hethongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_hethongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_hethongActionPerformed

    private void TF_nxbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_nxbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_nxbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSach().setVisible(true);
            }PN_themsach_mainmenu;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_dangxuat;
    private javax.swing.JButton BT_docgia;
    private javax.swing.JButton BT_hethong;
    private javax.swing.JButton BT_muontrasach;
    private javax.swing.JButton BT_reset;
    private javax.swing.JButton BT_sach;
    private javax.swing.JButton BT_save;
    private javax.swing.JButton BT_taikhoan;
    private javax.swing.JButton BT_themsach;
    private javax.swing.JButton BT_thongke;
    private javax.swing.JButton BT_thongtinsach;
    private javax.swing.JButton BT_trangchu;
    private javax.swing.JComboBox<String> CB_theloai;
    private javax.swing.JFormattedTextField FF_ngaynhap;
    private javax.swing.JFormattedTextField FF_trigia;
    private javax.swing.JLabel LB_Sach_menu;
    private javax.swing.JLabel LB_masach;
    private javax.swing.JLabel LB_namxuatban;
    private javax.swing.JLabel LB_ngaynhap;
    private javax.swing.JLabel LB_nxb;
    private javax.swing.JLabel LB_soluong;
    private javax.swing.JLabel LB_tacgia;
    private javax.swing.JLabel LB_tensach;
    private javax.swing.JLabel LB_theloai;
    private javax.swing.JLabel LB_trigia;
    private javax.swing.JPanel PN_themsach_info;
    private javax.swing.JPanel PN_themsach_info_chitiet;
    private javax.swing.JPanel PN_themsach_mainmenu;
    private javax.swing.JPanel PN_themsach_menu;
    private javax.swing.JSpinner SN_soluong;
    private javax.swing.JTextField TF_masach;
    private javax.swing.JTextField TF_namxuatban;
    private javax.swing.JTextField TF_nxb;
    private javax.swing.JTextField TF_tacgia;
    private javax.swing.JTextField TF_tensach;
    // End of variables declaration//GEN-END:variables
}
